oc_core:
    resource: "@OCCoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"