<?php

namespace OC\CoreBundle\Repository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{
    // Méthode pour récupérer les pays commencant par le mot en paramètre
    public function getCountryBeginWith($word)
    {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->select('c.nameFrFr')
            ->where('c.nameFrFr LIKE :word')
            ->setParameter('word', $word.'%')
            ->setMaxResults(10)
        ;

        return $qb
            ->getQuery()
            ->getArrayResult()
        ;

    }
}
