<?php

namespace OC\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
    // Méthode pour récupérer les pays commencant par le mot en paramètre
    public function getCountryBeginWith($word)
    {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->select('c.nameFrFr')
            ->where('c.nameFrFr LIKE :word')
            ->setParameter('word', $word.'%')
            ->setMaxResults(8)
        ;

        return $qb->getQuery()->getResult();

    }
}
