<?php

namespace OC\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
    // Méthode pour trouver les produits du panier
    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.id IN (:array)')
            ->setParameter('array', $array)
        ;
        
        return $qb->getQuery()->getResult();
    }
    
}
