<?php

namespace OC\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * VisitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorRepository extends EntityRepository
{
    // Méthode pour trouver les réservations du panier
    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('v')
            ->select('v')
            ->where('v.id IN (:array)')
            ->setParameter('array', $array)
        ;

        return $qb->getQuery()->getResult();
    }

    // Méthode pour trouver les billets d'un client
    public function getVisitorByCustomerId($customerId)
    {
        $qb = $this->createQueryBuilder('v')
            ->select('v.firstname, v.lastname, t.codeReservation, t.dateReservation, p.price')
            ->join('v.customer', 'c')
            ->join('v.price', 'p')
            ->leftJoin('v.ticket', 't')
            ->where('c.id = v.customer AND v.customer = :customerId')
            ->andWhere('t.id = v.ticket')
            ->setParameter('customerId', $customerId)
        ;

        return $qb->getQuery()->getResult();
    }
    
}
