oc_core_homepage:
    path:     /
    defaults: { _controller: OCCoreBundle:Core:index }

oc_core_pricelist:
    path:     /tarifs
    defaults: { _controller: OCCoreBundle:Core:pricelist }

oc_core_reservation:
    path:     /reservation
    defaults: { _controller: OCCoreBundle:Core:reservation }