oc_core_homepage:
    path:     /
    defaults: { _controller: OCCoreBundle:Core:index }

oc_core_pricelist:
    path:     /tarifs
    defaults: { _controller: OCCoreBundle:Core:pricelist }

oc_core_reservation:
    path:     /reservation
    defaults: { _controller: OCCoreBundle:Core:reservation }

oc_core_country:
    path:     /pays/{word}
    defaults: { _controller: OCCoreBundle:Core:completeCountry }

oc_core_cart_view:
    path:     /panier
    defaults: { _controller: OCCoreBundle:Cart:cart }

oc_core_cart_add:
    path:     /panier/ajout/{id}
    defaults: { _controller: OCCoreBundle:Cart:addCart }

oc_core_cart_remove:
    path:     /panier/supprime/{id}
    defaults: { _controller: OCCoreBundle:Cart:removeFromCart }

oc_core_cart_validated:
    path:     /remerciement
    defaults: { _controller: OCCoreBundle:Cart:validateCart }
   # methods:  [POST]

oc_core_cart_view_reservation:
    path:     /reservation/{codeReservation}
    defaults: { _controller: OCCoreBundle:Cart:viewReservation }


#paypal routing
oc_core_paypal:
    path: /paypal
    defaults: { _controller: OCCoreBundle:Paypal:setExpressCheckout }

oc_core_paypal_success:
    path: /paypal/success
    defaults: { _controller: OCCoreBundle:Paypal:getExpressCheckoutDetails }

oc_core_paypal_error:
    path: /paypal/error
    defaults: { _controller: OCCoreBundle:Paypal:errorPayment }

oc_core_paypal_payment:
    path: /paypal/payment
    defaults: { _controller: OCCoreBundle:Paypal:doExpressCheckoutPayment }

oc_core_paypal_validated:
    path: /paypal/validated
    defaults: { _controller: OCCoreBundle:Paypal:validatedCartPaypal }